---

- name: "Ensure {{ docker_compose_service_basedir }}"
  become: true
  ansible.builtin.file:
    path: "{{ docker_compose_service_basedir }}"
    state: directory

- name: "Include {{ ansible_service_mgr }}.yml"
  become: true
  ansible.builtin.include_tasks: "{{ ansible_service_mgr }}.yml"
