---

- name: "Ensure {{ docker_compose_service_basedir }}"
  become: true
  file:
    path: "{{ docker_compose_service_basedir }}"
    state: directory

- ansible.builtin.include_tasks: "{{ ansible_service_mgr }}.yml"
