---

- name: "Ensure {{ docker_compose_service_basedir }}"
  become: true
  ansible.builtin.file:
    path: "{{ docker_compose_service_basedir }}"
    state: directory
    mode: "0755"

- name: "Include tasks for {{ ansible_service_mgr }}"
  become: true
  ansible.builtin.include_tasks: "{{ ansible_service_mgr }}.yml"
