---
- name: Copy systemd configuration
  become: true
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{ docker_compose_service_name }}.service
    mode: "0644"
  notify:
    - Reload systemd daemon
    - Restart Service

- name: Enable systemd service
  become: true
  ansible.builtin.service:
    name: "{{ docker_compose_service_name }}"
    enabled: true
