---
- name: Copy systemd configuration
  become: true
  template:
    src: systemd.service
    dest: /etc/systemd/system/{{ docker_compose_service_name }}.service
  register: docker_compose_service_changed
  notify: restart service

- name: Reload systemd daemon
  become: true
  command: /bin/systemctl daemon-reload
  when: docker_compose_service_changed.changed

- name: Enable systemd service
  become: true
  service:
    name: "{{ docker_compose_service_name }}"
    enabled: true
