---
- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Service
  become: true
  ansible.builtin.service:
    name: "{{ docker_compose_service_name }}"
    state: restarted
