---

name: Ansible Lint
on: [push, pull_request]  # yamllint disable-line rule:truthy
jobs:
  ansiblelint:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            tasks/main.yml
          override-deps: |
            ansible-lint[core]==4.2.0
